spring:
  autoconfigure:
    exclude:
      - org.springframework.cloud.aws.autoconfigure.context.ContextInstanceDataAutoConfiguration
      - org.springframework.cloud.aws.autoconfigure.context.ContextStackAutoConfiguration
      - org.springframework.cloud.aws.autoconfigure.context.ContextRegionProviderAutoConfiguration

cloud:
  aws:
    region:
      static: us-east-1
      auto: false
    credentials:
      access-key: XXXX
      secret-key: XXXX
    end-point:
      uri: https://sqs.us-east-1.amazonaws.com/549485575026/spring-boot-poc